version: '3.8' 

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: front_end-container  
    ports:
      - "8048:3003"  
    restart: always  
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge
